rabbitmq:
  image: rabbitmq:3-management
  net: flannel
  ports:
    - "{{NGINX}}:4369:4369/tcp"
    - "{{NGINX}}:5671:5671/tcp"
    - "{{NGINX}}:5672:5672/tcp"
    - "{{NGINX}}:25672:25672/tcp"
    - "{{NGINX}}:15672:15672/tcp"
  size: L
  alauda_lb: ALB

zipkin:
  image: openzipkin/zipkin:2
  ports:
    - "{{NGINX}}:9411:9411/tcp"
  net: flannel
  size: L
  alauda_lb: ALB

eureka-server:
  image:  {{REGISTRY}}/spring-cloud-netflix-example-eureka-server
  hostname: eureka-server
  ports:
    - "{{NGINX}}:8761:8761/tcp"
  net: flannel
  size: L
  alauda_lb: ALB

config-server:
  image:  {{REGISTRY}}/spring-cloud-netflix-example-config-server
  links:
    - "eureka-server:eureka-server"
    - "rabbitmq:rabbitmq"
  ports:
    - "{{NGINX}}:8100:8100/tcp"
  net: flannel
  size: L
  alauda_lb: ALB

service-b:
  image:  {{REGISTRY}}/spring-cloud-netflix-example-service-b
  links:
    - "eureka-server:eureka-server"
    - "config-server:config-server"
    - "hystrix-dashboard:hystrix-dashboard"
    - "rabbitmq:rabbitmq"
    - "zipkin:zipkin"
  ports:
    - "{{NGINX}}:18082:8070/tcp"
  net: flannel
  size: L
  alauda_lb: ALB

service-a:
  image:  {{REGISTRY}}/spring-cloud-netflix-example-service-a
  links:
    - "eureka-server:eureka-server"
    - "config-server:config-server"
    - "service-b:service-b"
    - "hystrix-dashboard:hystrix-dashboard"
    - "rabbitmq:rabbitmq"
    - "zipkin:zipkin"
  ports:
    - "{{NGINX}}:18081:8080/tcp"
  net: flannel
  size: L
  alauda_lb: ALB

admin-dashboard:
  image:  {{REGISTRY}}/spring-cloud-netflix-example-admin-dashboard
  ports:
    - "{{NGINX}}:8040:8040/tcp"
  links:
    - "eureka-server:eureka-server"
    - "rabbitmq:rabbitmq"
    - "config-server:config-server"
    - "service-a:service-a"
    - "service-b:service-b"
    - "zuul:zuul"
    - "hystrix-dashboard:hystrix-dashboard"
  net: flannel
  size: L
  alauda_lb: ALB

zuul:
  image:  {{REGISTRY}}/spring-cloud-netflix-example-zuul
  ports:
    - "{{NGINX}}:8060:8060/tcp"
  links:
    - "eureka-server:eureka-server"
    - "config-server:config-server"
    - "service-a:service-a"
    - "rabbitmq:rabbitmq"
    - "zipkin:zipkin"
  net: flannel
  size: L
  alauda_lb: ALB

hystrix-dashboard:
  image:  {{REGISTRY}}/spring-cloud-netflix-example-hystrix-dashboard
  ports:
    - "{{NGINX}}:8050:8050/tcp"
  links:
    - "eureka-server:eureka-server"
  net: flannel
  size: L
  alauda_lb: ALB